openapi: 3.0.0
info:
  title: Certificate API
  version: 1.0.0
  description: API for CRUD operations on certificates.

paths:
  /certificates:
    post:
      summary: Create a new certificate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Certificate'
      responses:
        '201':
          description: Certificate created successfully.
        '400':
          description: Invalid input.

    get:
      summary: Retrieve a list of certificates
      responses:
        '200':
          description: A list of certificates.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Certificate'

  /certificates/{certificateId}:
    get:
      summary: Retrieve a specific certificate by ID
      parameters:
        - name: certificateId
          in: path
          required: true
          description: ID of the certificate to retrieve.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Certificate details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Certificate'
        '404':
          description: Certificate not found.

    put:
      summary: Update a specific certificate by ID
      parameters:
        - name: certificateId
          in: path
          required: true
          description: ID of the certificate to update.
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Certificate'
      responses:
        '200':
          description: Certificate updated successfully.
        '400':
          description: Invalid input.
        '404':
          description: Certificate not found.

    delete:
      summary: Delete a specific certificate by ID
      parameters:
        - name: certificateId
          in: path
          required: true
          description: ID of the certificate to delete.
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Certificate deleted successfully.
        '404':
          description: Certificate not found.

components:
  schemas:
    Certificate:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the certificate.
        certificateData:
          type: string
          format: byte
          description: Base64 encoded certificate data.
        expirationDate:
          type: string
          format: date-time
          description: Expiration date of the certificate.
